magdalena/__init__.py
__version__ = "0.3.1"

magdalena/app.py
# SPDX-FileCopyrightText: 2023 - 2024 GESIS - Leibniz-Institut für Sozialwissenschaften
# SPDX-FileContributor: Raniere Gaia Costa da Silva <Raniere.CostadaSilva@gesis.org>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

from logging.config import dictConfig
import os

from celery import Celery
from celery import Task
from flask import Flask

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", None)
CELERY_BACKEND_URL = os.getenv("CELERY_BACKEND_URL", None)

assert CELERY_BROKER_URL is not None, "CELERY_BROKER_URL can't be None"
assert CELERY_BACKEND_URL is not None, "CELERY_BACKEND_URL can't be None"

# Define the logging level
LOGGING_LEVEL = os.getenv("LOGGING_LEVEL", "INFO")
LOGGING_LEVEL = LOGGING_LEVEL.upper()

# Logging level must be one of the defined in https://docs.python.org/3/howto/logging.html#logging-levels
assert LOGGING_LEVEL in [
    "CRITICAL",
    "ERROR",
    "WARNING",
    "INFO",
    "DEBUG",
    "NOTSET",
], "Logging level is invalid"

# Configuring the logging
#
# https://docs.python.org/3/library/logging.config.html#configuration-dictionary-schema
dictConfig(
    {
        "version": 1,
        "disable_existing_loggers": True,
        "formatters": {
            "default": {
                "format": "[%(asctime)s] [%(levelname)s] %(message)s",
            }
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "default",
                "stream": "ext://sys.stdout",  # https://docs.python.org/3/library/logging.config.html#access-to-external-objects
            },
        },
        "loggers": {
            "gunicorn.error": {
                "handlers": ["console"],
                "level": LOGGING_LEVEL,
                "propagate": False,
            },
            "gunicorn.access": {
                "handlers": ["console"],
                "level": LOGGING_LEVEL,
                "propagate": False,
            },
        },
        "root": {"level": LOGGING_LEVEL, "handlers": ["console"]},
    }
)


def create_app():
    from .views import bp

    app = Flask(__name__)

    app.logger.info("Celery broker URL: %s", CELERY_BROKER_URL)
    app.logger.info("Celery backend URL: %s", CELERY_BACKEND_URL)

    app.config.from_mapping(
        CELERY=dict(
            broker_url=CELERY_BROKER_URL,
            result_backend=CELERY_BACKEND_URL,
            # task_ignore_result=True,
        ),
    )
    app.config.from_prefixed_env()
    celery_init_app(app)

    app.register_blueprint(bp)

    return app


def celery_init_app(app):
    from celery.utils.log import get_task_logger

    class FlaskTask(Task):
        def on_failure(self, exc, task_id, args, kwargs, einfo):
            logger = get_task_logger(__name__)

            logger.exception("Celery task failure!!!", exc_info=exc)

            super(FlaskTask, self).on_failure(exc, task_id, args, kwargs, einfo)

        def __call__(self, *args, **kwargs):
            with app.app_context():
                return self.run(*args, **kwargs)

    celery_app = Celery(app.name, task_cls=FlaskTask)
    celery_app.config_from_object(app.config["CELERY"])
    celery_app.set_default()
    app.extensions["celery"] = celery_app
    return celery_app

magdalena/views.py
# SPDX-FileCopyrightText: 2024 GESIS - Leibniz-Institut für Sozialwissenschaften
# SPDX-FileContributor: Raniere Gaia Costa da Silva <Raniere.CostadaSilva@gesis.org>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

import json
import os
import time

from celery.result import AsyncResult

from flask import Blueprint
from flask import request, render_template, send_file, send_from_directory
from flask import Response
from flask import current_app
from flask import stream_with_context

import jwt

authorization_required_from_env = os.getenv("AUTHORIZATION_REQUIRED", True)
if isinstance(authorization_required_from_env, str):
    authorization_required_from_env = authorization_required_from_env.lower()
    if authorization_required_from_env == "false":
        AUTHORIZATION_REQUIRED = False
    elif authorization_required_from_env == "true":
        AUTHORIZATION_REQUIRED = True
    else:
        AUTHORIZATION_REQUIRED = True
else:
    AUTHORIZATION_REQUIRED = authorization_required_from_env

if AUTHORIZATION_REQUIRED:
    from .pem import (
        KEYCLOAK_REALM,
        KEYCLOAK_CLIENT,
        KEYCLOAK_ISSUER,
        retrieve_public_key,
    )

from . import tasks

bp = Blueprint("tasks", __name__)


@bp.route("/keycloak.min.js")
def send_keycloak_adapter():
    return send_from_directory("/var/keycloak", "keycloak.min.js")


@bp.get("/download/<id>")
def download(id):
    result = AsyncResult(id)

    if result.ready() and result.successful():
        file_path = result.result
        if file_path:
            if file_path.endswith(".zip"):
                return send_file(
                    file_path,
                    mimetype="application/zip",
                    as_attachment=True,
                )
            elif file_path.endswith(".html"):
                return send_file(
                    file_path,
                    mimetype="text/html",
                    as_attachment=False,
                )
            else:
                return send_file(
                    file_path,
                    mimetype="text/plain",
                    as_attachment=False,
                )

    return "Not found", 404


@bp.get("/result/<id>")
def result(id):
    result = AsyncResult(id)
    ready = result.ready()
    current_app.logger.debug("Async Task ready() is %s", ready)

    successful = None
    if ready:
        successful = result.successful()
        current_app.logger.debug("Async Task successful() is %s", successful)

    payload = None
    if ready and successful:
        payload = result.result

    return {
        "ready": ready,
        "successful": successful,
        "value": payload,
    }


# To debug,
#
# @stream_with_context
# def poll_result(id):
#     current_current_app.logger.error(result)
@stream_with_context
def poll_result(id):
    # This is a generator and yield should be used to return data
    result = AsyncResult(id)

    while result.state not in ["SUCCESS", "FAILURE"]:
        data = {"state": result.state}
        yield f"data: {json.dumps(data)}\n\n"
        time.sleep(30)

        # Update for while
        result = AsyncResult(id)

    if result.state == "SUCCESS":
        data = {"state": result.state, "result": result.result}
        yield f"data: {json.dumps(data)}\n\n"
    else:
        data = {"state": result.state}
        yield f"data: {json.dumps(data)}\n\n"

    # Connection ends here.


@bp.get("/sse/result/<id>")
def result_sse(id):
    return Response(poll_result(id), mimetype="text/event-stream")


@bp.get("/")
def index():
    if AUTHORIZATION_REQUIRED:
        keycloak_scheme = os.getenv("FRONTEND_KEYCLOAK_SCHEME", None)
        if keycloak_scheme is None:
            keycloak_scheme = os.getenv("KEYCLOAK_SCHEME", None)
        current_app.logger.debug("keycloak_scheme = %s", keycloak_scheme)

        keycloak_domain = os.getenv("FRONTEND_KEYCLOAK_DOMAIN", None)
        if keycloak_domain is None:
            keycloak_domain = os.getenv("KEYCLOAK_DOMAIN", None)
        current_app.logger.debug("keycloak_domain = %s", keycloak_domain)

        return render_template(
            "index-authorization-required.html",
            keycloak_scheme=keycloak_scheme,
            keycloak_domain=keycloak_domain,
            keycloak_realm=KEYCLOAK_REALM,
            keycloak_client=KEYCLOAK_CLIENT,
        )

    return render_template("index.html")


@bp.post("/")
def build():
    if AUTHORIZATION_REQUIRED:
        JWT_ISSUER = os.getenv("JWT_ISSUER", KEYCLOAK_ISSUER)

        PUBLIC_KEY = retrieve_public_key()

        authorization = request.headers.get("Authorization")
        assert authorization, "Authorization is missing in header"

        authorization_scheme, authorization_token = authorization.split()
        assert authorization_scheme == "Bearer", "Authorization is missing in header"

        current_app.logger.debug("Validating JWT")
        current_app.logger.debug("\tExpected issuer: %s", JWT_ISSUER)
        current_app.logger.debug("\tJWT: %s", authorization_token)

        jwt.decode(
            authorization_token,
            key=PUBLIC_KEY,
            algorithms=["RS256"],
            options={"verify_aud": False},
            issuer=JWT_ISSUER,
        )

    celery_result = tasks.build.delay(request.json)
    return {"id": celery_result.id}

magdalena/templates/index-authorization-required.html
<!--
SPDX-FileCopyrightText: 2023 - 2024 GESIS - Leibniz-Institut für Sozialwissenschaften
SPDX-FileContributor: Raniere Gaia Costa da Silva <Raniere.CostadaSilva@gesis.org>

SPDX-License-Identifier: AGPL-3.0-or-later
-->

<!DOCTYPE html>
<html>
  <head>
    <title>magdalena</title>

    <script src="{{ url_for('tasks.send_keycloak_adapter') }}"></script>
    <script>
      const keycloak = new Keycloak({
        url: "{{keycloak_scheme}}://{{keycloak_domain}}",
        realm: "{{keycloak_realm}}",
        clientId: "{{keycloak_client}}",
      });

      async function main() {
        try {
          const authenticated = await keycloak.init({
            onLoad: "login-required",
          });
          console.debug(
            `User is ${authenticated ? "authenticated" : "not authenticated"}`
          );

          if (keycloak.authenticated) {
            console.debug(keycloak.token);
          }
        } catch (error) {
          console.error("Failed to initialize adapter:", error);
        }
      }

      main();
    </script>
  </head>
  <body>
    <h1>magdalena</h1>
    <form action="" method="post" id="form">
      <div>
        <label for="source_url">Source URL:</label><br />
        <input type="text" id="source_url" name="source_url" required />
      </div>
      <div>
        <label for="git_commit_id">Git Commit ID:</label><br />
        <input type="text" id="git_commit_id" name="git_commit_id" />
      </div>
      <div>
        <label for="filename">File in source:</label><br />
        <input type="text" id="filename" name="filename" />
      </div>
      <div>
        <label for="target_format">Select target format:</label><br />
        <select
          id="target_format"
          name="target_format"
          multiple
          size="4"
          required
        >
          <option value="md" disabled>Markdown</option>
          <option value="html" selected>HTML</option>
          <option value="qmd" disabled>Quarto</option>
          <option value="ipynb">Jupyter Notebook</option>
        </select>
      </div>
      <input type="submit" value="Submit" id="submit" />
    </form>
  </body>
  <script>
    async function submit(event) {
      event.preventDefault();

      document.getElementById("submit").disabled = true;

      console.debug("Preparing request ...");
      let html_form = document.getElementById("form");
      let form_data = new FormData(html_form);
      let form_json = {
        source_url: form_data.get("source_url"),
        git_commit_id: form_data.get("git_commit_id"),
        filename: form_data.get("filename"),
      };
      for (let key of ["target_format"]) {
        form_json[key] = form_data.getAll(key);
      }
      console.debug("Preparing request completed!");

      keycloak.updateToken(-1).then((data) => {
        console.debug(`JWT: ${keycloak.token}`);

        let tasks_build_domain_relative_url_string =
          "{{ url_for('tasks.build') }}";

        fetch(tasks_build_domain_relative_url_string, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${keycloak.token}`,
          },
          body: JSON.stringify(form_json),
        })
          .then((res) => {
            if (res.ok) {
              return res.json();
            }

            document.getElementById("submit").disabled = false;
            throw new Error(`${res.status} - ${res.statusText}`);
          })
          .then((data) => {
            console.debug("Starting server-sent event ...");

            let tasks_result_sse_domain_relative_url_string =
              "{{ url_for('tasks.result_sse', id='ID') }}";
            tasks_result_sse_domain_relative_url_string =
              tasks_result_sse_domain_relative_url_string.replace(
                "ID",
                data.id
              );

            const evtSource = new EventSource(
              tasks_result_sse_domain_relative_url_string
            );

            evtSource.onerror = (err) => {
              document.getElementById("submit").disabled = false;

              console.debug("Closing Server Sent Events connection!", err);

              // We might close the connection here on the bases that the connection ended because no more data will be send.
              evtSource.close();
            };

            evtSource.onmessage = (event) => {
              console.debug(event);
              message = JSON.parse(event.data);
              if (message.state === "SUCCESS") {
                console.debug(`Result: ${message.result}`);

                // We must close the connection here!
                evtSource.close();

                let tasks_download_domain_relative_url_string =
                  "{{ url_for('tasks.download', id='ID') }}";
                tasks_download_domain_relative_url_string =
                  tasks_download_domain_relative_url_string.replace(
                    "ID",
                    data.id
                  );

                console.info(
                  `Redirecting to ${tasks_download_domain_relative_url_string}`
                );
                window.location.href =
                  tasks_download_domain_relative_url_string;
              } else {
                console.debug(`State: ${message.state}`);
              }
            };
          });
      });
    }

    let html_form = document.getElementById("form");
    html_form.addEventListener("submit", submit);
  </script>
</html>

magdalena/templates/index.html
<!--
SPDX-FileCopyrightText: 2023 - 2024 GESIS - Leibniz-Institut für Sozialwissenschaften
SPDX-FileContributor: Raniere Gaia Costa da Silva <Raniere.CostadaSilva@gesis.org>

SPDX-License-Identifier: AGPL-3.0-or-later
-->

<!DOCTYPE html>
<html>
  <head>
    <title>magdalena</title>
  </head>
  <body>
    <h1>magdalena</h1>
    <form action="" method="post" id="form">
      <div>
        <label for="source_url">Source URL:</label><br />
        <input type="text" id="source_url" name="source_url" required />
      </div>
      <div>
        <label for="git_commit_id">Git Commit ID:</label><br />
        <input type="text" id="git_commit_id" name="git_commit_id" />
      </div>
      <div>
        <label for="filename">File in source:</label><br />
        <input type="text" id="filename" name="filename" />
      </div>
      <div>
        <label for="target_format">Select target format:</label><br />
        <select
          id="target_format"
          name="target_format"
          multiple
          size="4"
          required
        >
          <option value="md" disabled>Markdown</option>
          <option value="html" selected>HTML</option>
          <option value="qmd" disabled>Quarto</option>
          <option value="ipynb">Jupyter Notebook</option>
        </select>
      </div>
      <div>
        <label for="response">Select response format:</label><br />
        <select id="response" name="response" multiple size="2" required>
          <option value="download" selected>Download</option>
          <option value="forward" disabled>Forward</option>
        </select>
      </div>
      <input type="submit" value="Submit" id="submit" />
    </form>
  </body>
  <script>
    async function submit(event) {
      event.preventDefault();

      document.getElementById("submit").disabled = true;

      console.debug("Preparing request ...");
      let html_form = document.getElementById("form");
      let form_data = new FormData(html_form);
      let form_json = {
        source_url: form_data.get("source_url"),
        git_commit_id: form_data.get("git_commit_id"),
        filename: form_data.get("filename"),
        response: form_data.get("response"),
      };
      for (let key of ["target_format"]) {
        form_json[key] = form_data.getAll(key);
      }
      console.debug("Preparing request completed!");

      let tasks_build_domain_relative_url_string =
        "{{ url_for('tasks.build') }}";

      fetch(tasks_build_domain_relative_url_string, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(form_json),
      })
        .then((res) => {
          if (res.ok) {
            return res.json();
          }

          document.getElementById("submit").disabled = false;
          throw new Error(`${res.status} - ${res.statusText}`);
        })
        .then((data) => {
          console.debug("Starting server-sent event ...");

          let tasks_result_sse_domain_relative_url_string =
            "{{ url_for('tasks.result_sse', id='ID') }}";
          tasks_result_sse_domain_relative_url_string =
            tasks_result_sse_domain_relative_url_string.replace("ID", data.id);

          const evtSource = new EventSource(
            tasks_result_sse_domain_relative_url_string
          );

          evtSource.onerror = (err) => {
            document.getElementById("submit").disabled = false;

            console.debug("Closing Server Sent Events connection!", err);

            // We might close the connection here on the bases that the connection ended because no more data will be send.
            evtSource.close();
          };

          evtSource.onmessage = (event) => {
            console.debug(event);
            message = JSON.parse(event.data);
            if (message.state === "SUCCESS") {
              console.debug(`Result: ${message.result}`);

              // We must close the connection here!
              evtSource.close();

              let tasks_download_domain_relative_url_string =
                "{{ url_for('tasks.download', id='ID') }}";
              tasks_download_domain_relative_url_string =
                tasks_download_domain_relative_url_string.replace(
                  "ID",
                  data.id
                );

              console.info(
                `Redirecting to ${tasks_download_domain_relative_url_string}`
              );
              window.location.href = tasks_download_domain_relative_url_string;
            } else {
              console.debug(`State: ${message.state}`);
            }
          };
        });
    }

    let html_form = document.getElementById("form");
    html_form.addEventListener("submit", submit);
  </script>
</html>